// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: auth_service.proto

#include "auth_service.pb.h"
#include "auth_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace auth {

static const char* AuthService_method_names[] = {
  "/auth.AuthService/AuthenticateUser",
  "/auth.AuthService/RegisterUser",
};

std::unique_ptr< AuthService::Stub> AuthService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< AuthService::Stub> stub(new AuthService::Stub(channel, options));
  return stub;
}

AuthService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_AuthenticateUser_(AuthService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RegisterUser_(AuthService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status AuthService::Stub::AuthenticateUser(::grpc::ClientContext* context, const ::auth::AuthRequest& request, ::auth::AuthResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::auth::AuthRequest, ::auth::AuthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AuthenticateUser_, context, request, response);
}

void AuthService::Stub::async::AuthenticateUser(::grpc::ClientContext* context, const ::auth::AuthRequest* request, ::auth::AuthResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::auth::AuthRequest, ::auth::AuthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AuthenticateUser_, context, request, response, std::move(f));
}

void AuthService::Stub::async::AuthenticateUser(::grpc::ClientContext* context, const ::auth::AuthRequest* request, ::auth::AuthResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AuthenticateUser_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::auth::AuthResponse>* AuthService::Stub::PrepareAsyncAuthenticateUserRaw(::grpc::ClientContext* context, const ::auth::AuthRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::auth::AuthResponse, ::auth::AuthRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AuthenticateUser_, context, request);
}

::grpc::ClientAsyncResponseReader< ::auth::AuthResponse>* AuthService::Stub::AsyncAuthenticateUserRaw(::grpc::ClientContext* context, const ::auth::AuthRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAuthenticateUserRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AuthService::Stub::RegisterUser(::grpc::ClientContext* context, const ::auth::AuthRequest& request, ::auth::AuthResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::auth::AuthRequest, ::auth::AuthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RegisterUser_, context, request, response);
}

void AuthService::Stub::async::RegisterUser(::grpc::ClientContext* context, const ::auth::AuthRequest* request, ::auth::AuthResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::auth::AuthRequest, ::auth::AuthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterUser_, context, request, response, std::move(f));
}

void AuthService::Stub::async::RegisterUser(::grpc::ClientContext* context, const ::auth::AuthRequest* request, ::auth::AuthResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterUser_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::auth::AuthResponse>* AuthService::Stub::PrepareAsyncRegisterUserRaw(::grpc::ClientContext* context, const ::auth::AuthRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::auth::AuthResponse, ::auth::AuthRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RegisterUser_, context, request);
}

::grpc::ClientAsyncResponseReader< ::auth::AuthResponse>* AuthService::Stub::AsyncRegisterUserRaw(::grpc::ClientContext* context, const ::auth::AuthRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRegisterUserRaw(context, request, cq);
  result->StartCall();
  return result;
}

AuthService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AuthService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AuthService::Service, ::auth::AuthRequest, ::auth::AuthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AuthService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::auth::AuthRequest* req,
             ::auth::AuthResponse* resp) {
               return service->AuthenticateUser(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AuthService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AuthService::Service, ::auth::AuthRequest, ::auth::AuthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AuthService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::auth::AuthRequest* req,
             ::auth::AuthResponse* resp) {
               return service->RegisterUser(ctx, req, resp);
             }, this)));
}

AuthService::Service::~Service() {
}

::grpc::Status AuthService::Service::AuthenticateUser(::grpc::ServerContext* context, const ::auth::AuthRequest* request, ::auth::AuthResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AuthService::Service::RegisterUser(::grpc::ServerContext* context, const ::auth::AuthRequest* request, ::auth::AuthResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace auth
