// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: auth_service.proto
#ifndef GRPC_auth_5fservice_2eproto__INCLUDED
#define GRPC_auth_5fservice_2eproto__INCLUDED

#include "auth_service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace auth {

// Definition of the authentication service
class AuthService final {
 public:
  static constexpr char const* service_full_name() {
    return "auth.AuthService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Authenticates a user
    virtual ::grpc::Status AuthenticateUser(::grpc::ClientContext* context, const ::auth::AuthRequest& request, ::auth::AuthResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::auth::AuthResponse>> AsyncAuthenticateUser(::grpc::ClientContext* context, const ::auth::AuthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::auth::AuthResponse>>(AsyncAuthenticateUserRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::auth::AuthResponse>> PrepareAsyncAuthenticateUser(::grpc::ClientContext* context, const ::auth::AuthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::auth::AuthResponse>>(PrepareAsyncAuthenticateUserRaw(context, request, cq));
    }
    // Registers a new user
    virtual ::grpc::Status RegisterUser(::grpc::ClientContext* context, const ::auth::AuthRequest& request, ::auth::AuthResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::auth::AuthResponse>> AsyncRegisterUser(::grpc::ClientContext* context, const ::auth::AuthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::auth::AuthResponse>>(AsyncRegisterUserRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::auth::AuthResponse>> PrepareAsyncRegisterUser(::grpc::ClientContext* context, const ::auth::AuthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::auth::AuthResponse>>(PrepareAsyncRegisterUserRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Authenticates a user
      virtual void AuthenticateUser(::grpc::ClientContext* context, const ::auth::AuthRequest* request, ::auth::AuthResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AuthenticateUser(::grpc::ClientContext* context, const ::auth::AuthRequest* request, ::auth::AuthResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Registers a new user
      virtual void RegisterUser(::grpc::ClientContext* context, const ::auth::AuthRequest* request, ::auth::AuthResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RegisterUser(::grpc::ClientContext* context, const ::auth::AuthRequest* request, ::auth::AuthResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::auth::AuthResponse>* AsyncAuthenticateUserRaw(::grpc::ClientContext* context, const ::auth::AuthRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::auth::AuthResponse>* PrepareAsyncAuthenticateUserRaw(::grpc::ClientContext* context, const ::auth::AuthRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::auth::AuthResponse>* AsyncRegisterUserRaw(::grpc::ClientContext* context, const ::auth::AuthRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::auth::AuthResponse>* PrepareAsyncRegisterUserRaw(::grpc::ClientContext* context, const ::auth::AuthRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status AuthenticateUser(::grpc::ClientContext* context, const ::auth::AuthRequest& request, ::auth::AuthResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::auth::AuthResponse>> AsyncAuthenticateUser(::grpc::ClientContext* context, const ::auth::AuthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::auth::AuthResponse>>(AsyncAuthenticateUserRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::auth::AuthResponse>> PrepareAsyncAuthenticateUser(::grpc::ClientContext* context, const ::auth::AuthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::auth::AuthResponse>>(PrepareAsyncAuthenticateUserRaw(context, request, cq));
    }
    ::grpc::Status RegisterUser(::grpc::ClientContext* context, const ::auth::AuthRequest& request, ::auth::AuthResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::auth::AuthResponse>> AsyncRegisterUser(::grpc::ClientContext* context, const ::auth::AuthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::auth::AuthResponse>>(AsyncRegisterUserRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::auth::AuthResponse>> PrepareAsyncRegisterUser(::grpc::ClientContext* context, const ::auth::AuthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::auth::AuthResponse>>(PrepareAsyncRegisterUserRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void AuthenticateUser(::grpc::ClientContext* context, const ::auth::AuthRequest* request, ::auth::AuthResponse* response, std::function<void(::grpc::Status)>) override;
      void AuthenticateUser(::grpc::ClientContext* context, const ::auth::AuthRequest* request, ::auth::AuthResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void RegisterUser(::grpc::ClientContext* context, const ::auth::AuthRequest* request, ::auth::AuthResponse* response, std::function<void(::grpc::Status)>) override;
      void RegisterUser(::grpc::ClientContext* context, const ::auth::AuthRequest* request, ::auth::AuthResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::auth::AuthResponse>* AsyncAuthenticateUserRaw(::grpc::ClientContext* context, const ::auth::AuthRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::auth::AuthResponse>* PrepareAsyncAuthenticateUserRaw(::grpc::ClientContext* context, const ::auth::AuthRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::auth::AuthResponse>* AsyncRegisterUserRaw(::grpc::ClientContext* context, const ::auth::AuthRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::auth::AuthResponse>* PrepareAsyncRegisterUserRaw(::grpc::ClientContext* context, const ::auth::AuthRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_AuthenticateUser_;
    const ::grpc::internal::RpcMethod rpcmethod_RegisterUser_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Authenticates a user
    virtual ::grpc::Status AuthenticateUser(::grpc::ServerContext* context, const ::auth::AuthRequest* request, ::auth::AuthResponse* response);
    // Registers a new user
    virtual ::grpc::Status RegisterUser(::grpc::ServerContext* context, const ::auth::AuthRequest* request, ::auth::AuthResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_AuthenticateUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AuthenticateUser() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_AuthenticateUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AuthenticateUser(::grpc::ServerContext* /*context*/, const ::auth::AuthRequest* /*request*/, ::auth::AuthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAuthenticateUser(::grpc::ServerContext* context, ::auth::AuthRequest* request, ::grpc::ServerAsyncResponseWriter< ::auth::AuthResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_RegisterUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RegisterUser() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_RegisterUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterUser(::grpc::ServerContext* /*context*/, const ::auth::AuthRequest* /*request*/, ::auth::AuthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegisterUser(::grpc::ServerContext* context, ::auth::AuthRequest* request, ::grpc::ServerAsyncResponseWriter< ::auth::AuthResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_AuthenticateUser<WithAsyncMethod_RegisterUser<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_AuthenticateUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AuthenticateUser() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::auth::AuthRequest, ::auth::AuthResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::auth::AuthRequest* request, ::auth::AuthResponse* response) { return this->AuthenticateUser(context, request, response); }));}
    void SetMessageAllocatorFor_AuthenticateUser(
        ::grpc::MessageAllocator< ::auth::AuthRequest, ::auth::AuthResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::auth::AuthRequest, ::auth::AuthResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AuthenticateUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AuthenticateUser(::grpc::ServerContext* /*context*/, const ::auth::AuthRequest* /*request*/, ::auth::AuthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AuthenticateUser(
      ::grpc::CallbackServerContext* /*context*/, const ::auth::AuthRequest* /*request*/, ::auth::AuthResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_RegisterUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RegisterUser() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::auth::AuthRequest, ::auth::AuthResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::auth::AuthRequest* request, ::auth::AuthResponse* response) { return this->RegisterUser(context, request, response); }));}
    void SetMessageAllocatorFor_RegisterUser(
        ::grpc::MessageAllocator< ::auth::AuthRequest, ::auth::AuthResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::auth::AuthRequest, ::auth::AuthResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RegisterUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterUser(::grpc::ServerContext* /*context*/, const ::auth::AuthRequest* /*request*/, ::auth::AuthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RegisterUser(
      ::grpc::CallbackServerContext* /*context*/, const ::auth::AuthRequest* /*request*/, ::auth::AuthResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_AuthenticateUser<WithCallbackMethod_RegisterUser<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_AuthenticateUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AuthenticateUser() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_AuthenticateUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AuthenticateUser(::grpc::ServerContext* /*context*/, const ::auth::AuthRequest* /*request*/, ::auth::AuthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_RegisterUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RegisterUser() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_RegisterUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterUser(::grpc::ServerContext* /*context*/, const ::auth::AuthRequest* /*request*/, ::auth::AuthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_AuthenticateUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AuthenticateUser() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_AuthenticateUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AuthenticateUser(::grpc::ServerContext* /*context*/, const ::auth::AuthRequest* /*request*/, ::auth::AuthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAuthenticateUser(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_RegisterUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RegisterUser() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_RegisterUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterUser(::grpc::ServerContext* /*context*/, const ::auth::AuthRequest* /*request*/, ::auth::AuthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegisterUser(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AuthenticateUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AuthenticateUser() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AuthenticateUser(context, request, response); }));
    }
    ~WithRawCallbackMethod_AuthenticateUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AuthenticateUser(::grpc::ServerContext* /*context*/, const ::auth::AuthRequest* /*request*/, ::auth::AuthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AuthenticateUser(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RegisterUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RegisterUser() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RegisterUser(context, request, response); }));
    }
    ~WithRawCallbackMethod_RegisterUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegisterUser(::grpc::ServerContext* /*context*/, const ::auth::AuthRequest* /*request*/, ::auth::AuthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RegisterUser(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AuthenticateUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AuthenticateUser() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::auth::AuthRequest, ::auth::AuthResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::auth::AuthRequest, ::auth::AuthResponse>* streamer) {
                       return this->StreamedAuthenticateUser(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AuthenticateUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AuthenticateUser(::grpc::ServerContext* /*context*/, const ::auth::AuthRequest* /*request*/, ::auth::AuthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAuthenticateUser(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::auth::AuthRequest,::auth::AuthResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RegisterUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RegisterUser() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::auth::AuthRequest, ::auth::AuthResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::auth::AuthRequest, ::auth::AuthResponse>* streamer) {
                       return this->StreamedRegisterUser(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RegisterUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RegisterUser(::grpc::ServerContext* /*context*/, const ::auth::AuthRequest* /*request*/, ::auth::AuthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRegisterUser(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::auth::AuthRequest,::auth::AuthResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_AuthenticateUser<WithStreamedUnaryMethod_RegisterUser<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_AuthenticateUser<WithStreamedUnaryMethod_RegisterUser<Service > > StreamedService;
};

}  // namespace auth


#endif  // GRPC_auth_5fservice_2eproto__INCLUDED
