apiVersion: v1
kind: Service
metadata:
  name: game-server-service
spec:
  type: LoadBalancer # Для UDP часто используют LoadBalancer или NodePort
  selector:
    app: game-server
  ports:
  - name: game-udp
    protocol: UDP
    port: 9999       # Внешний порт
    targetPort: game-udp # Имя порта из Deployment
  - name: game-metrics # Для доступа к метрикам игрового сервера, если нужно извне кластера
    protocol: TCP
    port: 8001
    targetPort: game-metrics
