apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: | # Сюда будет вставлено содержимое файла deployment/nginx/nginx.conf
    user nginx;
    worker_processes auto;

    error_log /var/log/nginx/error.log warn;
    pid       /var/run/nginx.pid;

    events {
        worker_connections 1024;
    }

    stream {
        upstream auth_servers {
            # Обнаружение сервисов K8s должно разрешить auth-server-service в правильный IP-адрес
            # Использование FQDN (полного доменного имени) для надежности:
            server auth-server-service.default.svc.cluster.local:8888; 
            # Или просто: server auth-server-service:8888; если в том же пространстве имен
        }

        server {
            listen 8888; # Nginx слушает этот TCP-порт
            proxy_pass auth_servers;
            proxy_timeout 5s;
            proxy_connect_timeout 1s;
        }

        upstream game_servers {
             # Использование FQDN для надежности:
            server game-server-service.default.svc.cluster.local:9999;
            # Или просто: server game-server-service:9999; если в том же пространстве имен
        }

        server {
            listen 9999 udp; # Nginx слушает этот UDP-порт
            proxy_pass game_servers;
        }
    }
