apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer
spec:
  type: LoadBalancer # Это будет внешний IP для доступа к Nginx
  selector:
    app: nginx-ingress
  ports:
  - name: auth
    protocol: TCP
    port: 8888       # Внешний порт, который слушает LoadBalancer
    targetPort: nginx-auth-tcp # Порт на подах Nginx
  - name: game
    protocol: UDP
    port: 9999
    targetPort: nginx-game-udp
  # - name: http
  #   protocol: TCP
  #   port: 80
  #   targetPort: nginx-http # Если Nginx слушает HTTP
