# deployment/kubernetes/redis_configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |
    # Включаем AOF (Append Only File) для большей надежности данных
    appendonly yes
    appendfilename "appendonly.aof"
    # appendfsync everysec # Синхронизировать каждую секунду (хороший компромисс между скоростью и надежностью)
    # appendfsync always # Очень медленно, но максимально надежно (синхронизировать при каждой записи)
    appendfsync no # Полагаться на операционную систему для синхронизации; быстро, но менее надежно при сбое питания сервера

    # Снэпшоты RDB (Redis Database Backup)
    # Сохранять, если за 900 секунд изменился хотя бы 1 ключ
    save 900 1
    # Сохранять, если за 300 секунд изменилось хотя бы 10 ключей
    save 300 10
    # Сохранять, если за 60 секунд изменилось хотя бы 10000 ключей
    save 60 10000

    # Имя файла для снэпшотов RDB
    dbfilename dump.rdb

    # Директория для хранения файлов AOF и RDB.
    # В Kubernetes это будет путь внутри смонтированного Persistent Volume.
    dir /data

    # Установка пароля для Redis (настоятельно рекомендуется для безопасности)
    # requirepass ВашНадежныйПароль # Замените на 실제 пароль
    # Если пароль установлен, его необходимо будет указывать во всех клиентах Redis, подключающихся к серверу.
