# deployment/kubernetes/redis_backup_cronjob.yaml
apiVersion: batch/v1
kind: CronJob # В Kubernetes 1.21+ (для старых версий batch/v1beta1)
metadata:
  name: redis-backup-cron
spec:
  schedule: "0 2 * * *" # Запускать каждый день в 2 часа ночи
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: redis-backup
            image: alpine:latest # Используем простой образ Alpine, добавляем утилиты если нужно
            command: ["/bin/sh", "-c"]
            args:
            - |
              # Устанавливаем rsync или другие утилиты, если нужно для копирования на удаленный хост
              # apk add --no-cache rsync openssh-client
              # Содержимое скрипта backup_redis.sh можно вставить сюда напрямую
              # или скопировать его в образ и запустить.
              # Для простоты, вставим сюда часть логики.
              
              BACKUP_DIR_TARGET="/mnt/backupstorage/redis" # Это должен быть смонтированный внешний сторадж
              REDIS_DATA_MOUNT="/redis-pvc-data" # Путь к данным Redis PVC
              TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
              RDB_FILE="dump.rdb"

              echo "Redis Backup CronJob started at $(date)"
              if [ ! -d "$REDIS_DATA_MOUNT" ]; then
                echo "Error: Redis data directory $REDIS_DATA_MOUNT not mounted or not found!"
                exit 1
              fi
              
              mkdir -p ${BACKUP_DIR_TARGET}

              if [ -f "${REDIS_DATA_MOUNT}/${RDB_FILE}" ]; then
                  cp "${REDIS_DATA_MOUNT}/${RDB_FILE}" "${BACKUP_DIR_TARGET}/dump-${TIMESTAMP}.rdb"
                  echo "RDB file backup created: ${BACKUP_DIR_TARGET}/dump-${TIMESTAMP}.rdb"
                  # Здесь можно добавить команду для загрузки в облачное хранилище
                  # например, aws s3 cp ${BACKUP_DIR_TARGET}/dump-${TIMESTAMP}.rdb s3://your-backup-bucket/redis/
              else
                  echo "RDB file ${REDIS_DATA_MOUNT}/${RDB_FILE} not found."
              fi
              echo "Redis Backup CronJob finished at $(date)"

            volumeMounts:
            - name: redis-persistent-storage # Том с данными Redis
              mountPath: /redis-pvc-data 
              readOnly: true # Монтируем только для чтения, чтобы не повредить данные
            - name: backup-target-storage # Том для хранения бэкапов (например, NFS, облачный сторадж)
              mountPath: /mnt/backupstorage 
              # Этот том должен быть настроен отдельно (например, hostPath для тестов, или облачный PV)
          volumes:
          - name: redis-persistent-storage
            persistentVolumeClaim:
              claimName: redis-pvc # Тот же PVC, что использует Redis
          - name: backup-target-storage 
            emptyDir: {} # ЗАГЛУШКА! В реальности это должен быть PersistentVolume для бэкапов
                         # например, NFS, AWS EBS, GCE Persistent Disk, смонтированный сюда.
                         # Использование emptyDir означает, что бэкапы будут удалены вместе с подом CronJob.
                         # Это нужно заменить на реальное хранилище.
